### ISSUE TITLE
if i want The training input data is four channels, because my six-channel data is spliced ​​from six single-channel 2D images. How should I modify the code? I do not have a mask annotation file. Can I use this code?

### ISSUE THREAD

**Issue by watertianyi** [shirowalker/UCAD#12]

**Comment by jiaq-liu** [comment]
> _No description provided._

This code is difficult to handle data other than RGB images. Mask labeling needs to be processed on RGB images using SAM, and the other pre-trained models in the code are also unable to handle 6-channel data.

**Comment by watertianyi** [comment]
@shirowalker 
Because a test object needs to be photographed six times with different light sources to show defects, which is equivalent to collecting six images. Do you have any better way to do this? Because different defects appear in different forms under different light sources, and the reaction Data diversity

**Comment by jiaq-liu** [comment]
@watertianyi 
It sounds like images under different lighting conditions can be separately analyzed, and the results of six detections can be unified to make a judgment. If calculating AUC-ROC, the maximum value of the six anomaly maps can be taken. If it is binary classification, an AND(&) operation can be performed (if one of the images is abnormal, the object is judged to be abnormal).

**Comment by watertianyi** [comment]
@shirowalker Is it more time-consuming to reason with six pictures than with a single picture?

**Comment by jiaq-liu** [comment]
@watertianyi 
Yes, it seems that we can only process the six images separately. Even if we treat them as multiple channels and process them together, the computational load won't be reduced.
