### ISSUE TITLE
能看一下复现的结果么，很奇怪损失有负数，而且结果感觉也不对

### ISSUE THREAD

**Issue by Karma1628** [shirowalker/UCAD#14]
![image](https://github.com/user-attachments/assets/ea7a9821-f7e5-41a0-8b35-ec841d37a97c)
![image](https://github.com/user-attachments/assets/1251a562-ebc4-4f63-87f5-98c0f1f38187)

复现的过程是直接解压了文件中的zip文件，没有用sam训，然后放进了mvtec2d所在的文件夹，按照readme中的命令行参数配置的运行结果
[dec_20241107_230831.log](https://github.com/user-attachments/files/17672247/dec_20241107_230831.log)
训练的过程我用logging记录了一下，看看很奇怪，损失有负数，而且结果很不理想，可以帮忙看看么

**Comment by jiaq-liu** [comment]
@Karma1628 你好，从日志中可以看出初始的image_auc就非常低，应该和训练无关。损失有负数是正常的，可以参见 https://github.com/shirowalker/UCAD/issues/13 。结果不理想的问题看上去和 https://github.com/shirowalker/UCAD/issues/9 一致，有两个同学都遇到过这个问题，分别是更换了服务器和pytorch版本解决的，所以我估计可能是pytorch或CUDA版本的问题。先确定pytorch和依赖一致，CUDA在11.3以上应该就可以了。

**Comment by Karma1628** [comment]
好的，感谢感谢~

**Comment by Karma1628** [comment]
确实是版本的问题hha，已解决，感谢
