### ISSUE TITLE
FM指标

### ISSUE THREAD

**Issue by Alchemist-LiuJiahui** [shirowalker/UCAD#16]
FM指标具体是如何实现的，请问在代码中有给出吗？我没有找到！谢谢

**Comment by jiaq-liu** [comment]
@the-unkown-user 你好，FM在代码里没有输出。可以参见readme"The final output will consist of two parts, with the lower metrics representing the final results, and the difference between them and the higher metrics results is denoted as FM."

**Comment by Alchemist-LiuJiahui** [comment]
好的，我看看，感谢！

**Comment by Alchemist-LiuJiahui** [comment]
![image](https://github.com/user-attachments/assets/6b15ed71-9361-4624-a6e7-3d07ca28de08)
请问你说的是这两个输出吗？还是说要跑一下你注释掉的代码？打扰您了，感谢！

**Comment by jiaq-liu** [comment]
@the-unkown-user 是这个两个输出，运行的时候终端里也会显示两个输出结果，跟这个保存起来的是一样的。

**Comment by Alchemist-LiuJiahui** [comment]
那在计算差异表示FM的时候是使用的哪个指标呢？instance_auroc还是pixel_ap，或是其他，或是均值？

**Comment by jiaq-liu** [comment]
@the-unkown-user FM是模型的遗忘程度，不是某个单一的指标，instance_auroc和pixel_ap都有对应的FM。

**Comment by Alchemist-LiuJiahui** [comment]
了解了，感谢，感谢
