### ISSUE TITLE
 Doubt about the "Last Subdataset" Mentioned in the Paper

### ISSUE THREAD

**Issue by Kathy1214** [shirowalker/UCAD#17]
你好，请问一下论文中的Image-level AUROC数据表写到了是last subdataset上训练的，这个last subdataset是指什么呢？因为注意到表格中的其他方法比如patchcore或者DREAM，这些方法的数据要比他们本身论文得出的数据低很多。所以想请教一下这个最后的子数据集是怎样得到或者说是对原mvtec ad数据集怎么处理的呢？

**Comment by jiaq-liu** [comment]
@Kathy1214 你好，论文总体是采用了持续学习的设定。last subdataset指的是持续学习的过程中训练的最后一个子类。Patchcore和DRAEM本身不存在持续学习场景下的防遗忘机制，因此性能会比较差。实验中将MVTec AD拆分成了15个不同种类的子数据集依次进行无回放的训练。具体可以参考一下论文Method的Unsupervised Continual AD Problem Defnition部分。
