### ISSUE TITLE
关于模型的几个问题

### ISSUE THREAD

**Issue by bonerush** [shirowalker/UCAD#18]
首先感谢作者大大能抽空看一下这个issue，我对您这个模型非常感兴趣!
Q1：SAM是如何用于引导特征空间压缩的，在代码中的体现是在哪里？
Q2：为什么作者会想到用sam来压缩特征空间，具体有什么启发吗？
Q3：CPM是不是用于给vit输入提示词的？我看了代码在prompt部分，分为g_prompt，e_prompt，这两个具体的区别在哪里？

**Comment by jiaq-liu** [comment]
@bonerush 你好，感谢关注，关于这几个问题。
A1: SAM引导特征空间压缩是通过对比学习实现的，具体是先使用SAM对训练集的图像进行了纹理的划分，然后将根据纹理的不同进行了对比学习，将相同纹理的特征拉近，不同纹理的特征拉远。代码上是在 https://github.com/shirowalker/UCAD/blob/main/patchcore/vision_transformer.py#L717 部分实现的 
A2: 想用SAM来压缩特征空间是在其他实验中想到的，一开始想利用SAM做一个有一定泛化性的异常分割模型，通过在异常合成数据集上有监督的训练得到一个理想的结果，后来实验失败了，但发现SAM分割出来的结果对于纹理比较敏感，这点可以拿来进行特征压缩。
A3: CPM是用于给ViT提供prompt(也是你说的提示词)和特定的knowledge(也就是memory bank)的，g_prompt和e_prompt也是一开始想借助 https://github.com/JH-LEE-KR/dualprompt-pytorch 学习一些异常数据的共性和特性，让不同的数据集共享g_prompt，各自有一些e_prompt。但后来实验发现很难找到共性，所以不同的子数据集完全分开了，导致用的g_prompt和e_prompt都不一样。现在体现出来的结果就是g_prompt和e_prompt其实没有区别。
