### ISSUE TITLE
莫名报错

### ISSUE THREAD

**Issue by EWAN9709** [shirowalker/UCAD#2]
作者大大，能否帮忙看下这个报错呢？

![image](https://github.com/shirowalker/UCAD/assets/82500501/edd1ebfc-f2bf-406c-ab51-da1da8b6ba93)

**Comment by shirowalker** [comment]
感觉是timm版本的问题，版本不一致导致超参不一样了。把timm改成0.6.7试试看看吧

**Comment by shirowalker** [comment]
> 作者大大，能否帮忙看下这个报错呢？
> 
> ![image](https://private-user-images.githubusercontent.com/82500501/320246911-edd1ebfc-f2bf-406c-ab51-da1da8b6ba93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTY1MTAsIm5iZiI6MTcxMjQ1NjIxMCwicGF0aCI6Ii84MjUwMDUwMS8zMjAyNDY5MTEtZWRkMWViZmMtZjJiZi00MDZjLWFiNTEtZGExZGE4YjZiYTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyMTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNDk4ZGM3M2NlODEyMjEyNGU3Y2Q3NjRjM2VmZWRlYmRlMTQzMWQ3MWI3YmFmMjgwYTU1OWYwNDYzNmM1NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vkjEQoHhW3CvY0xxs2cLPwV_w5-8LxBoMpqnJSqy7IM)
感觉是timm版本的问题，版本不一致导致超参不一样了。把timm改成0.6.7试试看看吧

**Comment by ddddfdcx** [comment]
解决了吗 我也遇到这个问题了

**Comment by Zan0115** [comment]
Changing timm version to 0.6.7 will solve this problem.
