### ISSUE TITLE
关于AUROC

### ISSUE THREAD

**Issue by boringKey** [shirowalker/UCAD#20]
您好，请问图中的UniAD对于zipper的结果，是在学习完第15个任务后，仅在zipper类这一个任务上进行检测，还是在全部的15个任务上进行检测，得到的0.997的结果呢？
![WeChat97317530b3ea9f216b365b35289b0917](https://github.com/user-attachments/assets/88fbed4c-899c-4657-91e4-29c41716ba61)

**Comment by jiaq-liu** [comment]
@boringKey 是在学完第15个任务后，仅在zipper类这一个任务上进行检测的结果，在全部的15个任务上进行检测的结果是average，也是表中15个类的均值。

**Comment by boringKey** [comment]
抱歉，还有一个疑问请您解惑：这张表格的数据，是模型一次性先将15个任务顺序学习完毕之后，再在每一个单独的任务进行的测试，而得到的结果吗？

**Comment by jiaq-liu** [comment]
@boringKey 这张表格的数据是按顺序将15个任务学习完后，分别测试得到的结果。后面的avg FM是按顺序学习15个任务的过程中，每个任务最好的结果，与最后这个均值的差值。
