### ISSUE TITLE
The result of training directly with SAM's segmented mask map is not good

### ISSUE THREAD

**Issue by fat-921** [shirowalker/UCAD#3]
Hello author, I use your code for training and drawing segmentation diagram. Instead of using the original diagram for training, you use the mask diagram divided by SAM. As a result, the resulting diagram is not good, which makes me very confused。
![image](https://github.com/shirowalker/UCAD/assets/66895706/5e4ef013-702e-4405-b41f-98339d3062dc)
orin_img:
![image](https://github.com/shirowalker/UCAD/assets/66895706/d13e3142-da4a-4674-ad59-ec8283a56403)
I would like to ask what should be done to get the results in the paper?

**Comment by shirowalker** [comment]
> Hello author, I use your code for training and drawing segmentation diagram. Instead of using the original diagram for training, you use the mask diagram divided by SAM. As a result, the resulting diagram is not good, which makes me very confused。 ![image](https://private-user-images.githubusercontent.com/66895706/320717098-5e4ef013-702e-4405-b41f-98339d3062dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDU4NTAsIm5iZiI6MTcxMjY0NTU1MCwicGF0aCI6Ii82Njg5NTcwNi8zMjA3MTcwOTgtNWU0ZWYwMTMtNzAyZS00NDA1LWI0MWYtOTgzMzlkMzA2MmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2NTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ODM4NWU0YmFhN2I1MTgwNzk3YmJkY2Y5YzIxOTgwZjVjYWI5MWQxMWU4YTZkNjAzOTcyZTZmNjY2NDM4NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cSXhJZBRd2x-7fp7znvnKFA7JAMCTeiMoCfMvKU9B0k) orin_img: ![image](https://private-user-images.githubusercontent.com/66895706/320717590-d13e3142-da4a-4674-ad59-ec8283a56403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDU4NTAsIm5iZiI6MTcxMjY0NTU1MCwicGF0aCI6Ii82Njg5NTcwNi8zMjA3MTc1OTAtZDEzZTMxNDItZGE0YS00Njc0LWFkNTktZWM4MjgzYTU2NDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2NTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZDJjZjdlOGY1YzgzZDY4ZjExZGNlY2I3ZDFiMDJiOWQwOWFmZjhmOTA3NGFlNmM2ZDEwZDcxODkwNTQ0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jFkrTXQ26bxoOBrimb8THKt2RmxF-AoDLU2Upu4FbMU) I would like to ask what should be done to get the results in the paper?

I think maybe you misunderstand something. In UCAD, we just use mask from SAM for contrastive learning. You should keep both "mvtec2d" directory and "mvtec2d-sam-b" directory. And "mvtec2d" should be used as second column of your diagram.
