### ISSUE TITLE
Can't recognize do echo

### ISSUE THREAD

**Issue by ddddfdcx** [shirowalker/UCAD#5]
![1713775437544](https://github.com/shirowalker/UCAD/assets/75150351/7066eb13-1046-4ff6-93dd-8e7cfd1e98c0)

When we run the code and configure the environment variables, we encounter the problem that do echo cannot be recognized. Is there a specific solution here? Thank you.

**Comment by boringKey** [comment]
Hi, I got the same question with you. Could share your solution please? Thank you!!!
