### ISSUE TITLE
sam_vit_b_01ec64.pth文件

### ISSUE THREAD

**Issue by hh30222** [shirowalker/UCAD#6]
parser.add_argument('--sam_checkpoint', default='/hhd3/ljq/checkpoints/sam_vit_b_01ec64.pth') # checkpoint path for sam
对于代码里面的这个sam_vit_b_01ec64.pth文件，是不是没有给出

**Comment by shirowalker** [comment]
> parser.add_argument('--sam_checkpoint', default='/hhd3/ljq/checkpoints/sam_vit_b_01ec64.pth') # checkpoint path for sam 对于代码里面的这个sam_vit_b_01ec64.pth文件，是不是没有给出

是的，可以直接使用segment anythingde的模型。在https://github.com/facebookresearch/segment-anything网页中。具体链接为：https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth
