### ISSUE TITLE
What‘s the problem?

### ISSUE THREAD

**Issue by FuNz-0** [shirowalker/UCAD#7]
![Snipaste_2024-06-04_16-06-30](https://github.com/shirowalker/UCAD/assets/45970865/74052df9-cc91-41ef-8dba-abf62c09725f)

**Comment by shirowalker** [comment]
> ![Snipaste_2024-06-04_16-06-30](https://private-user-images.githubusercontent.com/45970865/336360672-74052df9-cc91-41ef-8dba-abf62c09725f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODg3OTksIm5iZiI6MTcxNzQ4ODQ5OSwicGF0aCI6Ii80NTk3MDg2NS8zMzYzNjA2NzItNzQwNTJkZjktY2M5MS00MWVmLThkYmEtYWJmNjJjMDk3MjVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4MDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODg5NzcwOTRiZGIzMTU3ODc0MWQ2MGY1NTI1ZWYzMTc2YmRhOTQ0NDQ3YTdlMjE0M2YwNTgxYzRhZWI0OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvaCOR-opLZODg33wtBDOvO5pRa71zgcZw1E-Jw5BXc)

Maybe you didn't run the code according to the instructions in the readme. From the screenshot, it seems that the problem is that the parameter settings are missing.

**Comment by FuNz-0** [comment]
> > ![Snipaste_2024-06-04_16-06-30](https://private-user-images.githubusercontent.com/45970865/336360672-74052df9-cc91-41ef-8dba-abf62c09725f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODg3OTksIm5iZiI6MTcxNzQ4ODQ5OSwicGF0aCI6Ii80NTk3MDg2NS8zMzYzNjA2NzItNzQwNTJkZjktY2M5MS00MWVmLThkYmEtYWJmNjJjMDk3MjVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4MDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODg5NzcwOTRiZGIzMTU3ODc0MWQ2MGY1NTI1ZWYzMTc2YmRhOTQ0NDQ3YTdlMjE0M2YwNTgxYzRhZWI0OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvaCOR-opLZODg33wtBDOvO5pRa71zgcZw1E-Jw5BXc)
> 
> Maybe you didn't run the code according to the instructions in the readme. From the screenshot, it seems that the problem is that the parameter settings are missing.

![Snipaste_2024-06-04_17-00-42](https://github.com/shirowalker/UCAD/assets/45970865/a01bda9d-7cd4-4531-82a2-4160ae224631)
What parameters are missed?

**Comment by shirowalker** [comment]
> > > ![Snipaste_2024-06-04_16-06-30](https://private-user-images.githubusercontent.com/45970865/336360672-74052df9-cc91-41ef-8dba-abf62c09725f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODg3OTksIm5iZiI6MTcxNzQ4ODQ5OSwicGF0aCI6Ii80NTk3MDg2NS8zMzYzNjA2NzItNzQwNTJkZjktY2M5MS00MWVmLThkYmEtYWJmNjJjMDk3MjVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4MDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODg5NzcwOTRiZGIzMTU3ODc0MWQ2MGY1NTI1ZWYzMTc2YmRhOTQ0NDQ3YTdlMjE0M2YwNTgxYzRhZWI0OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvaCOR-opLZODg33wtBDOvO5pRa71zgcZw1E-Jw5BXc)
> > 
> > 
> > Maybe you didn't run the code according to the instructions in the readme. From the screenshot, it seems that the problem is that the parameter settings are missing.
> 
> ![Snipaste_2024-06-04_17-00-42](https://private-user-images.githubusercontent.com/45970865/336380725-a01bda9d-7cd4-4531-82a2-4160ae224631.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTI2NjYsIm5iZiI6MTcxNzQ5MjM2NiwicGF0aCI6Ii80NTk3MDg2NS8zMzYzODA3MjUtYTAxYmRhOWQtN2NkNC00NTMxLTgyYTItNDE2MGFlMjI0NjMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjc1MjMwM2U1NzUxZWQ1YmQ1YWI3ZDU5NmNiMDA5MjY4NTk2YjkxYjFmN2EwZmI2OTU2MDgzZTlhOGY2N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuzPnLBc46tWGxk1gFhHWGBLJLR4jL2jjYDQcAIEK3s) What parameters are missed?

I can't tell what the problem is based on the two screenshots. The first screenshot seems to just show you the format of the command. I looked at the second screenshot carefully and it is consistent with the readme. The code can run normally. If you need my help in debugging, I need more information, such as the complete error message.

**Comment by FuNz-0** [comment]
> > > > ![Snipaste_2024-06-04_16-06-30](https://private-user-images.githubusercontent.com/45970865/336360672-74052df9-cc91-41ef-8dba-abf62c09725f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODg3OTksIm5iZiI6MTcxNzQ4ODQ5OSwicGF0aCI6Ii80NTk3MDg2NS8zMzYzNjA2NzItNzQwNTJkZjktY2M5MS00MWVmLThkYmEtYWJmNjJjMDk3MjVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4MDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODg5NzcwOTRiZGIzMTU3ODc0MWQ2MGY1NTI1ZWYzMTc2YmRhOTQ0NDQ3YTdlMjE0M2YwNTgxYzRhZWI0OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvaCOR-opLZODg33wtBDOvO5pRa71zgcZw1E-Jw5BXc)
> > > 
> > > 
> > > Maybe you didn't run the code according to the instructions in the readme. From the screenshot, it seems that the problem is that the parameter settings are missing.
> > 
> > 
> > ![Snipaste_2024-06-04_17-00-42](https://private-user-images.githubusercontent.com/45970865/336380725-a01bda9d-7cd4-4531-82a2-4160ae224631.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTI2NjYsIm5iZiI6MTcxNzQ5MjM2NiwicGF0aCI6Ii80NTk3MDg2NS8zMzYzODA3MjUtYTAxYmRhOWQtN2NkNC00NTMxLTgyYTItNDE2MGFlMjI0NjMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjc1MjMwM2U1NzUxZWQ1YmQ1YWI3ZDU5NmNiMDA5MjY4NTk2YjkxYjFmN2EwZmI2OTU2MDgzZTlhOGY2N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuzPnLBc46tWGxk1gFhHWGBLJLR4jL2jjYDQcAIEK3s) What parameters are missed?
> 
> I can't tell what the problem is based on the two screenshots. The first screenshot seems to just show you the format of the command. I looked at the second screenshot carefully and it is consistent with the readme. The code can run normally. If you need my help in debugging, I need more information, such as the complete error message.

![Snipaste_2024-06-04_17-31-30](https://github.com/shirowalker/UCAD/assets/45970865/ad9c3422-7a6d-4b31-9191-6c91e6d3e817)
没有任何报错，只有Warning

**Comment by shirowalker** [comment]
> > > > > ![Snipaste_2024-06-04_16-06-30](https://private-user-images.githubusercontent.com/45970865/336360672-74052df9-cc91-41ef-8dba-abf62c09725f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODg3OTksIm5iZiI6MTcxNzQ4ODQ5OSwicGF0aCI6Ii80NTk3MDg2NS8zMzYzNjA2NzItNzQwNTJkZjktY2M5MS00MWVmLThkYmEtYWJmNjJjMDk3MjVmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4MDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODg5NzcwOTRiZGIzMTU3ODc0MWQ2MGY1NTI1ZWYzMTc2YmRhOTQ0NDQ3YTdlMjE0M2YwNTgxYzRhZWI0OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uvaCOR-opLZODg33wtBDOvO5pRa71zgcZw1E-Jw5BXc)
> > > > 
> > > > 
> > > > Maybe you didn't run the code according to the instructions in the readme. From the screenshot, it seems that the problem is that the parameter settings are missing.
> > > 
> > > 
> > > ![Snipaste_2024-06-04_17-00-42](https://private-user-images.githubusercontent.com/45970865/336380725-a01bda9d-7cd4-4531-82a2-4160ae224631.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTI2NjYsIm5iZiI6MTcxNzQ5MjM2NiwicGF0aCI6Ii80NTk3MDg2NS8zMzYzODA3MjUtYTAxYmRhOWQtN2NkNC00NTMxLTgyYTItNDE2MGFlMjI0NjMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjc1MjMwM2U1NzUxZWQ1YmQ1YWI3ZDU5NmNiMDA5MjY4NTk2YjkxYjFmN2EwZmI2OTU2MDgzZTlhOGY2N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuzPnLBc46tWGxk1gFhHWGBLJLR4jL2jjYDQcAIEK3s) What parameters are missed?
> > 
> > 
> > I can't tell what the problem is based on the two screenshots. The first screenshot seems to just show you the format of the command. I looked at the second screenshot carefully and it is consistent with the readme. The code can run normally. If you need my help in debugging, I need more information, such as the complete error message.
> 
> ![Snipaste_2024-06-04_17-31-30](https://private-user-images.githubusercontent.com/45970865/336392866-ad9c3422-7a6d-4b31-9191-6c91e6d3e817.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTM4OTgsIm5iZiI6MTcxNzQ5MzU5OCwicGF0aCI6Ii80NTk3MDg2NS8zMzYzOTI4NjYtYWQ5YzM0MjItN2E2ZC00YjMxLTkxOTEtNmM5MWU2ZDNlODE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MzMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZWYxZDg1YTIxYTlkNTIzNTBhNGJlNjQ1NDRjM2I4YjY1NTJiNTRlNWJmOWY3YmU1NTI0NDhhNGJjODAzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wpkru--rdc2hWWBibZN-kKq8s1Jz_D8RTWVAmGhjHKw) 没有任何报错，只有Warning

这类warning我没有遇到过，所以有可能是环境版本的问题。
我用的环境是：python>=3.8, torch>=1.12, CUDA>=11.3, timm==0.6.7 。
其中这个warning可能和timm的版本有关，可能是由于timm版本问题导致ViT没有正确初始化，加载预设的checkpoint，导致代码直接退出。
如果确定timm版本没有错误的话还得单步调试，进一步确定是在哪里退出的才好判断。

**Comment by boringKey** [comment]
Hi, I got the same question with you. Could share your solution please? Thank you!!!

**Comment by jiaq-liu** [comment]
> Hi, I got the same question with you. Could share your solution please? Thank you!!!

I think it may be a problem with the environment version.
The environment I use is: python>=3.8, torch>=1.12, CUDA>=11.3, timm==0.6.7.
This warning may be related to the timm version. It may be due to the timm version problem that ViT fails to initialize and load the preset checkpoint correctly, causing the code to exit directly.
