### ISSUE TITLE
关于模型的一些疑惑

### ISSUE THREAD

**Issue by HULEI7** [shirowalker/UCAD#8]
您好，我认为这篇工作非常有意义！但是关于模型我有一些疑虑，从代码来看，本文相当于是为每一个类学习一个特征空间，这其实和在非持续学习设定下每一个单独进行学习是类似的，可是本文的指标要比PatchCore原文低很多（按理来说在这样相似的设定下指标应该差不多）。可能是我对代码和论文的理解有一些偏差，麻烦您可以解答一下我的疑虑，感谢！

**Comment by shirowalker** [comment]
> 您好，我认为这篇工作非常有意义！但是关于模型我有一些疑虑，从代码来看，本文相当于是为每一个类学习一个特征空间，这其实和在非持续学习设定下每一个单独进行学习是类似的，可是本文的指标要比PatchCore原文低很多（按理来说在这样相似的设定下指标应该差不多）。可能是我对代码和论文的理解有一些偏差，麻烦您可以解答一下我的疑虑，感谢！

从本质上来说，本文和PatchCore最大的区别是做了特征的压缩。论文中的SAM就是用于引导特征空间压缩的。在压缩之后，本文可以利用极小的memory bank实现高性能的异常检测，而PatchCore在同样大小的memory bank下则会表现出严重的性能下降。

**Comment by HULEI7** [comment]
好的理解了，感谢您及时和清晰的回答！
