### ISSUE TITLE
测试结果不符合预期

### ISSUE THREAD

**Issue by wadegrc** [shirowalker/UCAD#9]
你好，我根据readme中的步骤在mvtec2d上训练，没有改代码，不过发现损失基本不下降，而且测试集上的image_roc以及pixel_roc和论文中的结果差的很大。
训练script为
`datapath=/data/grc/UCAD/mvtec2d/
datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper')
dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done))

CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath
`

**Comment by wadegrc** [comment]
![roc](https://github.com/user-attachments/assets/f28e66bb-d341-4716-81fc-6260659d5919)
样例
![bottle_test_broken_large_000_hoi](https://github.com/user-attachments/assets/d00b7db9-ec87-424c-8e7d-5d7ffe009a1a)
![bottle_test_broken_large_000_mask](https://github.com/user-attachments/assets/2c5401de-9ab0-43c3-8cb0-04d743e7cb25)
![bottle_test_broken_large_000_org](https://github.com/user-attachments/assets/8fbeafbc-4cb8-47bf-b4fd-52259334a6af)
![bottle_test_broken_large_000_segmentation](https://github.com/user-attachments/assets/af156af5-9079-4077-b863-fd3fc9c704d1)

**Comment by jiaq-liu** [comment]
> 你好，我根据readme中的步骤在mvtec2d上训练，没有改代码，不过发现损失基本不下降，而且测试集上的image_roc以及pixel_roc和论文中的结果差的很大。 训练script为 `datapath=/data/grc/UCAD/mvtec2d/ datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper') dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]}"; do echo '-d '$dataset; done))
> 
> CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath `

你好，如果没有修改代码的话，大概率是没有正确设置训练数据的关系，文章中除了MVTec AD数据集外还用到了SAM对数据集进行处理，并得到分割图(仓库中已提供)，这里需要将分割图放在MVTec AD数据集的的同一目录下。

**Comment by wadegrc** [comment]
![image](https://github.com/user-attachments/assets/4c5a1fba-7d73-4a52-b546-65006fab1597)
![image](https://github.com/user-attachments/assets/32247a13-897c-4627-b3bb-589002ce269d)
是放在同一目录下（用的仓库提供的），应该也正确加载了，对比损失是能计算的，prompt的梯度也有，但是损失不下降。

**Comment by wadegrc** [comment]
> > 你好，我根据readme中的步骤在mvtec2d上训练，没有改代码，不过发现损失基本不下降，而且测试集上的image_roc以及pixel_roc和论文中的结果差的很大。 训练script为 `datapath=/data/grc/UCAD/mvtec2d/ datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper') dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]}"; do echo '-d '$dataset; done))
> > CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath `
> 
> 你好，如果没有修改代码的话，大概率是没有正确设置训练数据的关系，文章中除了MVTec AD数据集外还用到了SAM对数据集进行处理，并得到分割图(仓库中已提供)，这里需要将分割图放在MVTec AD数据集的的同一目录下。

刚重新clone仓库跑了一遍，把源数据和sam处理后的数据放好后，直接训练结果还是一样，其他都没动。

**Comment by jiaq-liu** [comment]
> > > 你好，我根据readme中的步骤在mvtec2d上训练，没有改代码，不过发现损失基本不下降，而且测试集上的image_roc以及pixel_roc和论文中的结果差的很大。 训练script为 `datapath=/data/grc/UCAD/mvtec2d/ datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper') dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]}"; do echo '-d '$dataset; done)) CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath `
> > 
> > 
> > 你好，如果没有修改代码的话，大概率是没有正确设置训练数据的关系，文章中除了MVTec AD数据集外还用到了SAM对数据集进行处理，并得到分割图(仓库中已提供)，这里需要将分割图放在MVTec AD数据集的的同一目录下。
> 
> 刚重新clone仓库跑了一遍，把源数据和sam处理后的数据放好后，直接训练结果还是一样，其他都没动。

运行时 dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]} 这里是不是错了，应该是
`dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done)) `。大概率还是数据集的设置有问题，从结果上来看，即使完全不训练也不会得到这么低的数值，而且limited和unlimited的结果是完全一致的，这种情况非常罕见。``

**Comment by wadegrc** [comment]
> > > > 你好，我根据readme中的步骤在mvtec2d上训练，没有改代码，不过发现损失基本不下降，而且测试集上的image_roc以及pixel_roc和论文中的结果差的很大。 训练script为 `datapath=/data/grc/UCAD/mvtec2d/ datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper') dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]}"; do echo '-d '$dataset; done)) CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath `
> > > 
> > > 
> > > 你好，如果没有修改代码的话，大概率是没有正确设置训练数据的关系，文章中除了MVTec AD数据集外还用到了SAM对数据集进行处理，并得到分割图(仓库中已提供)，这里需要将分割图放在MVTec AD数据集的的同一目录下。
> > 
> > 
> > 刚重新clone仓库跑了一遍，把源数据和sam处理后的数据放好后，直接训练结果还是一样，其他都没动。
> 
> 运行时 dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]} 这里是不是错了，应该是 `dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done)) `。大概率还是数据集的设置有问题，从结果上来看，即使完全不训练也不会得到这么低的数值，而且limited和unlimited的结果是完全一致的，这种情况非常罕见。``

```
datapath=/data/grc/UCAD/mvtec2d/
datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper')
dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done))

CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath

```
![image](https://github.com/user-attachments/assets/94d2af0f-44d7-45ae-8fea-9718059eefed)

应该没错，复制的readme中的，除了修改下路径。

**Comment by jiaq-liu** [comment]
> > > > > 你好，我根据readme中的步骤在mvtec2d上训练，没有改代码，不过发现损失基本不下降，而且测试集上的image_roc以及pixel_roc和论文中的结果差的很大。 训练script为 `datapath=/data/grc/UCAD/mvtec2d/ datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper') dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]}"; do echo '-d '$dataset; done)) CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath `
> > > > 
> > > > 
> > > > 你好，如果没有修改代码的话，大概率是没有正确设置训练数据的关系，文章中除了MVTec AD数据集外还用到了SAM对数据集进行处理，并得到分割图(仓库中已提供)，这里需要将分割图放在MVTec AD数据集的的同一目录下。
> > > 
> > > 
> > > 刚重新clone仓库跑了一遍，把源数据和sam处理后的数据放好后，直接训练结果还是一样，其他都没动。
> > 
> > 
> > 运行时 dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]} 这里是不是错了，应该是 `dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done)) `。大概率还是数据集的设置有问题，从结果上来看，即使完全不训练也不会得到这么低的数值，而且limited和unlimited的结果是完全一致的，这种情况非常罕见。``
> 
> ```
> datapath=/data/grc/UCAD/mvtec2d/
> datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper')
> dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done))
> 
> CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath
> ```
> 
> 应该没错，复制的readme中的，除了修改下路径。

这个情况确实很罕见，我暂时也看不出来是什么导致的。感觉需要逐步排查，比如输出一下训练的时候使用的图片和分割图看是否对应。但是初步看起来应该不是训练的问题，可以尝试把训练epoch改成0，看是不是还是一样的，如果一样的话也就是说退化版的PatchCore也会面临相同的问题，这样的话可以推测问题可能出在数据集、ViT的checkpoint或者推理分割上。如果epoch改成0结果变好了，反而是训练过程中出现了问题，可以再排查是不是图像和分割图的不一致或者其他问题。

**Comment by wadegrc** [comment]
> > > > > > 你好，我根据readme中的步骤在mvtec2d上训练，没有改代码，不过发现损失基本不下降，而且测试集上的image_roc以及pixel_roc和论文中的结果差的很大。 训练script为 `datapath=/data/grc/UCAD/mvtec2d/ datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper') dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]}"; do echo '-d '$dataset; done)) CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath `
> > > > > 
> > > > > 
> > > > > 你好，如果没有修改代码的话，大概率是没有正确设置训练数据的关系，文章中除了MVTec AD数据集外还用到了SAM对数据集进行处理，并得到分割图(仓库中已提供)，这里需要将分割图放在MVTec AD数据集的的同一目录下。
> > > > 
> > > > 
> > > > 刚重新clone仓库跑了一遍，把源数据和sam处理后的数据放好后，直接训练结果还是一样，其他都没动。
> > > 
> > > 
> > > 运行时 dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]} 这里是不是错了，应该是 `dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done)) `。大概率还是数据集的设置有问题，从结果上来看，即使完全不训练也不会得到这么低的数值，而且limited和unlimited的结果是完全一致的，这种情况非常罕见。``
> > 
> > 
> > ```
> > datapath=/data/grc/UCAD/mvtec2d/
> > datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper')
> > dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done))
> > 
> > CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 应该没错，复制的readme中的，除了修改下路径。
> 
> 这个情况确实很罕见，我暂时也看不出来是什么导致的。感觉需要逐步排查，比如输出一下训练的时候使用的图片和分割图看是否对应。但是初步看起来应该不是训练的问题，可以尝试把训练epoch改成0，看是不是还是一样的，如果一样的话也就是说退化版的PatchCore也会面临相同的问题，这样的话可以推测问题可能出在数据集、ViT的checkpoint或者推理分割上。如果epoch改成0结果变好了，反而是训练过程中出现了问题，可以再排查是不是图像和分割图的不一致或者其他问题。

试了epoch改为0，同时不引入e-prompt，只用预训练vit的特征，结果还是一样，此外从上面四张图可以看到预测的热力图不准确，而groudtruth的分割图是对应原图的，数据集应该没问题，所以问题是不是出在提取特征之后的处理上，像压缩特征。

**Comment by jiaq-liu** [comment]
> > > > > > > 你好，我根据readme中的步骤在mvtec2d上训练，没有改代码，不过发现损失基本不下降，而且测试集上的image_roc以及pixel_roc和论文中的结果差的很大。 训练script为 `datapath=/data/grc/UCAD/mvtec2d/ datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper') dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]}"; do echo '-d '$dataset; done)) CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath `
> > > > > > 
> > > > > > 
> > > > > > 你好，如果没有修改代码的话，大概率是没有正确设置训练数据的关系，文章中除了MVTec AD数据集外还用到了SAM对数据集进行处理，并得到分割图(仓库中已提供)，这里需要将分割图放在MVTec AD数据集的的同一目录下。
> > > > > 
> > > > > 
> > > > > 刚重新clone仓库跑了一遍，把源数据和sam处理后的数据放好后，直接训练结果还是一样，其他都没动。
> > > > 
> > > > 
> > > > 运行时 dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]} 这里是不是错了，应该是 `dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done)) `。大概率还是数据集的设置有问题，从结果上来看，即使完全不训练也不会得到这么低的数值，而且limited和unlimited的结果是完全一致的，这种情况非常罕见。``
> > > 
> > > 
> > > ```
> > > datapath=/data/grc/UCAD/mvtec2d/
> > > datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper')
> > > dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done))
> > > 
> > > CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 应该没错，复制的readme中的，除了修改下路径。
> > 
> > 
> > 这个情况确实很罕见，我暂时也看不出来是什么导致的。感觉需要逐步排查，比如输出一下训练的时候使用的图片和分割图看是否对应。但是初步看起来应该不是训练的问题，可以尝试把训练epoch改成0，看是不是还是一样的，如果一样的话也就是说退化版的PatchCore也会面临相同的问题，这样的话可以推测问题可能出在数据集、ViT的checkpoint或者推理分割上。如果epoch改成0结果变好了，反而是训练过程中出现了问题，可以再排查是不是图像和分割图的不一致或者其他问题。
> 
> 试了epoch改为0，同时不引入e-prompt，只用预训练vit的特征，结果还是一样，此外从上面四张图可以看到预测的热力图不准确，而groudtruth的分割图是对应原图的，数据集应该没问题，所以问题是不是出在提取特征之后的处理上，像压缩特征。

如果说epoch为0还是不对的话，那应该不单是压缩的问题，或者说完全抽取错了特征，因为epoch为0的时候相当于使用限制memory版本的PatchCore进行异常检测，而且此时有不限制memory的对应结果。
从截图中给出的一个例子也可以看到，是否限制memory大小对结果不影响，image_auroc均为0.4706，包括其他数值也是一样的，这才是最奇怪的一点。仅仅从结果上来看的话，unlimited的image_auroc显然是不符合预期的，表明memory bank大小为196或是1960并没有产生任何影。如果说memory196和1960完全没有区别，或许是现有数据集中可以采集的特征数小于等于196，或许是这两个参数完全没有起作用。
半年到两周前还有五六位同学测试过代码，复现过程中都没有出现这种情况，这期间仓库唯一的修改是结果存储部分，对输出应该也没有影响，所以感觉更像是数据集配置的问题。感觉可以从两个角度出发找问题：1. 下载上次修改前的版本 (https://github.com/shirowalker/UCAD/tree/65f153758fd9b72c86d9074fe91b15ffe8ba51f2) 2. 可以打一些断点，看看数据集的输入输出是否正常。

**Comment by wadegrc** [comment]
> > > > > > > > 你好，我根据readme中的步骤在mvtec2d上训练，没有改代码，不过发现损失基本不下降，而且测试集上的image_roc以及pixel_roc和论文中的结果差的很大。 训练script为 `datapath=/data/grc/UCAD/mvtec2d/ datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper') dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]}"; do echo '-d '$dataset; done)) CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath `
> > > > > > > 
> > > > > > > 
> > > > > > > 你好，如果没有修改代码的话，大概率是没有正确设置训练数据的关系，文章中除了MVTec AD数据集外还用到了SAM对数据集进行处理，并得到分割图(仓库中已提供)，这里需要将分割图放在MVTec AD数据集的的同一目录下。
> > > > > > 
> > > > > > 
> > > > > > 刚重新clone仓库跑了一遍，把源数据和sam处理后的数据放好后，直接训练结果还是一样，其他都没动。
> > > > > 
> > > > > 
> > > > > 运行时 dataset_flags=( ( f o r d a t a s e t i n " {datasets[@]} 这里是不是错了，应该是 `dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done)) `。大概率还是数据集的设置有问题，从结果上来看，即使完全不训练也不会得到这么低的数值，而且limited和unlimited的结果是完全一致的，这种情况非常罕见。``
> > > > 
> > > > 
> > > > ```
> > > > datapath=/data/grc/UCAD/mvtec2d/
> > > > datasets=('bottle' 'cable' 'capsule' 'carpet' 'grid' 'hazelnut' 'leather' 'metal_nut' 'pill' 'screw' 'tile' 'toothbrush' 'transistor' 'wood' 'zipper')
> > > > dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '$dataset; done))
> > > > 
> > > > CUDA_VISIBLE_DEVICES=0 python3 run_ucad.py --gpu 0 --seed 0 --memory_size 196 --log_group IM224_UCAD_L5_P01_D1024_M196 --save_segmentation_images --log_project MVTecAD_Results results ucad -b wideresnet50 -le layer2 -le layer3 --faiss_on_gpu --pretrain_embed_dimension 1024 --target_embed_dimension 1024 --anomaly_scorer_num_nn 1 --patchsize 1 sampler -p 0.1 approx_greedy_coreset dataset --resize 224 --imagesize 224 "${dataset_flags[@]}" mvtec $datapath
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 应该没错，复制的readme中的，除了修改下路径。
> > > 
> > > 
> > > 这个情况确实很罕见，我暂时也看不出来是什么导致的。感觉需要逐步排查，比如输出一下训练的时候使用的图片和分割图看是否对应。但是初步看起来应该不是训练的问题，可以尝试把训练epoch改成0，看是不是还是一样的，如果一样的话也就是说退化版的PatchCore也会面临相同的问题，这样的话可以推测问题可能出在数据集、ViT的checkpoint或者推理分割上。如果epoch改成0结果变好了，反而是训练过程中出现了问题，可以再排查是不是图像和分割图的不一致或者其他问题。
> > 
> > 
> > 试了epoch改为0，同时不引入e-prompt，只用预训练vit的特征，结果还是一样，此外从上面四张图可以看到预测的热力图不准确，而groudtruth的分割图是对应原图的，数据集应该没问题，所以问题是不是出在提取特征之后的处理上，像压缩特征。
> 
> 如果说epoch为0还是不对的话，那应该不单是压缩的问题，或者说完全抽取错了特征，因为epoch为0的时候相当于使用限制memory版本的PatchCore进行异常检测，而且此时有不限制memory的对应结果。 从截图中给出的一个例子也可以看到，是否限制memory大小对结果不影响，image_auroc均为0.4706，包括其他数值也是一样的，这才是最奇怪的一点。仅仅从结果上来看的话，unlimited的image_auroc显然是不符合预期的，表明memory bank大小为196或是1960并没有产生任何影。如果说memory196和1960完全没有区别，或许是现有数据集中可以采集的特征数小于等于196，或许是这两个参数完全没有起作用。 半年到两周前还有五六位同学测试过代码，复现过程中都没有出现这种情况，这期间仓库唯一的修改是结果存储部分，对输出应该也没有影响，所以感觉更像是数据集配置的问题。感觉可以从两个角度出发找问题：1. 下载上次修改前的版本 (https://github.com/shirowalker/UCAD/tree/65f153758fd9b72c86d9074fe91b15ffe8ba51f2) 2. 可以打一些断点，看看数据集的输入输出是否正常。

换台服务器，数据集，模型，代码都没变，从3090的机器上换到V100，结果就对了。

**Comment by pyqjw** [comment]
遇到同样问题了

**Comment by jiaq-liu** [comment]
> 遇到同样问题了

如果检查代码，数据集，给定的mask数据都没有问题的话，也可以换一下机器试试

**Comment by pyqjw** [comment]
问题解决了，大概率是pytorch版本问题，换了个版本号一致的环境就行了

**Comment by Karma1628** [comment]
> 问题解决了，大概率是pytorch版本问题，换了个版本号一致的环境就行了

可以问一下你的torch和cuda的版本号么

**Comment by pyqjw** [comment]
> > 问题解决了，大概率是pytorch版本问题，换了个版本号一致的环境就行了
> 
> 可以问一下你的torch和cuda的版本号么

torch==1.12.1+cu113 environment.yaml里的

**Comment by Karma1628** [comment]
> > > 问题解决了，大概率是pytorch版本问题，换了个版本号一致的环境就行了
> > 
> > 
> > 可以问一下你的torch和cuda的版本号么
> 
> torch==1.12.1+cu113 environment.yaml里的

好的 谢谢
